name: Daily Grants Scraper

on:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install requests

    - name: Run Scraper
      run: |
        python grants_scraper.py

        - name: Upload CSV Output
        uses: actions/upload-artifact@v3.1.3
        with:
          name: grants-output
          path: grants_*.csv